[package]
name = "wora_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
wasmtime = "21.0.1"
wasi-common = "21.0.1"
zip = "2.1.3"
toml = "0.8.14"
clap_derive = "4.5.5"
clap = { version = "4.5.7", features = ["derive"] }
utils = { workspace = true }
